[[session]]
name = "the cafe"
path = "~/Documents/obsidian/The Cafe/"
startup_command = "nvim -c 'autocmd VimEnter * Telescope find_files'"

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "nvim -c 'autocmd VimEnter * Telescope find_files'"

[[session]]
name = "tmux config"
path = "~"
startup_command = "nvim .tmux.conf"

[[session]]
name = "fish config"
path = "~/.config/fish"
startup_command = "nvim config.fish"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
