[[session]]
name = "the cafe"
path = "~/Documents/obsidian/The Cafe/"
startup_command = "nvim -c 'autocmd VimEnter * Telescope find_files'"

[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "nvim -c 'autocmd VimEnter * Telescope find_files'"
