# use prefix-I to install below packages

# remap prefix
unbind C-b
set -g prefix c-a
bind c-a send-prefix

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'bobcats/everforest-tmux'
# set -g @plugin 'nordtheme/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

# set -g @everforest_theme 'dark-soft'
# set -g @everforest_window_tabs_enabled on # this wasn't enabled previously

# set navigation keys to be vim-like
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Source .tmux.conf as suggested in `man tmux`
bind R source-file '~/.tmux.conf'

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# for fixing colors using fish/alacritty/tmux
# You can use tmux-256color, however it's not installed by default on macOS
set -g default-terminal screen-256color 
# if your echo $TERM outside of alacritty isn't alacritty, place this $TERM thing instead(it should be xterm-256color otherwise)
set -ga terminal-overrides ",alacritty:RGB" 

# Allows clicking to change windows and panes
set -g mouse on

# skip "kill-pane 1? (y/n)" prompt
bind-key x kill-pane 

# better visual and yanking options
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# set panes to open in cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# set keybind to open sesh
bind-key "K" display-popup -E -w 40% "sesh connect \"$(
  sesh list -i | gum filter --limit 1 --placeholder 'pick a session' --prompt='⚡'
)\""

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
